source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'Mercurio_Example' do
  pod 'Mercurio', :path => '../'

  target 'Mercurio_Tests' do
    inherit! :search_paths

    
  end
end
