source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'Mercurio_Example', :exclusive => true do
    pod "Mercurio", :path => "../"
end

target 'Mercurio_Tests', :exclusive => true do
    pod "Mercurio", :path => "../"
end
